import { TERRAFORM_REQUIRED_VERSION } from "./terraform-aws.ts";

/**
 * Terraform scaffolding for the Google Cloud reference stack.
 *
 * Pure string builders — no runtime dependencies. Emitted by
 * `storyshelf server init` when the deploy target is `gcp`, alongside the
 * standard `server.ts` / `worker.ts` / `package.json` files.
 *
 * Reference stack: Cloud Run (app + worker) + GCS bucket (storybook
 * bundles) + Pub/Sub topic + pull subscription with dead-lettering +
 * Cloud SQL Postgres + Secret Manager + Identity Platform tenant (only
 * when `identity_tenant` is set) + Cloud DNS (only when `domain_name`
 * is set, with automatic managed TLS via the domain mapping).
 *
 * Output contract (stable keys, parsed by CI — see `GCP_TERRAFORM_OUTPUT_KEYS`):
 * keys are always present; values are `""` when the resource is not
 * provisioned for the optional inputs.
 */

/** Options for the GCP Terraform scaffold. */
export interface GcpTerraformOptions {
  /** Project slug, used as a name prefix for all resources. */
  project: string;
  /** Existing GCP project ID (APIs, billing, IAM live here). */
  gcpProjectId: string;
  /** GCP region, e.g. `us-central1`. */
  location: string;
  /** Public domain for the app. Empty leaves DNS out entirely. */
  domainName?: string;
  /** Identity Platform tenant display name. Empty skips identity. */
  identityTenant?: string;
}

/** A generated file: relative path → contents. */
export type TerraformFiles = Record<string, string>;

/**
 * Stable `terraform output -json` keys. CI (`live-cloud.yml`) parses these;
 * renaming a key is a breaking change — the unit tests pin this list.
 */
export const GCP_TERRAFORM_OUTPUT_KEYS: readonly string[] = [
  "database_url",
  "gcs_bucket",
  "identity_tenant_id",
  "pubsub_subscription",
  "pubsub_topic",
  "run_url",
];

function header(): string {
  return `# Generated by \`storyshelf server init --target gcp\`. Do not edit by hand;\n# re-run the scaffold or edit the generator in @storyshelf/cli.\n\n`;
}

export function generateGcpVersions(): string {
  return `${header()}terraform {
  required_version = "${TERRAFORM_REQUIRED_VERSION}"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = ">= 6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}

provider "google" {
  project = var.gcp_project_id
  region  = var.location
}
`;
}

export function generateGcpVariables(): string {
  return `${header()}variable "project" {
  description = "Project slug, used as a name prefix for all resources."
  type        = string
}

variable "gcp_project_id" {
  description = "Existing GCP project ID (APIs, billing, and IAM live here)."
  type        = string
}

variable "location" {
  description = "GCP region for all resources."
  type        = string
  default     = "us-central1"
}

variable "domain_name" {
  description = "Public domain for the app (Cloud DNS + domain mapping). Empty skips DNS."
  type        = string
  default     = ""
}

variable "identity_tenant" {
  description = "Identity Platform tenant display name. Empty skips identity."
  type        = string
  default     = ""
}
`;
}

export function generateGcpMain(): string {
  return `${header()}# Enable every API the stack touches. disable_on_destroy stays
# default (true) so CI teardown also releases the API bindings.
locals {
  slug = lower(var.project)
  apis = toset([
    "run.googleapis.com",
    "sqladmin.googleapis.com",
    "pubsub.googleapis.com",
    "storage.googleapis.com",
    "secretmanager.googleapis.com",
    "dns.googleapis.com",
    "identitytoolkit.googleapis.com",
  ])
}

resource "google_project_service" "apis" {
  for_each = local.apis
  project  = var.gcp_project_id
  service  = each.value
}
`;
}

export function generateGcpApp(): string {
  return `${header()}# App with public ingress. Image is a placeholder: build and push
# the scaffolded Dockerfile (Artifact Registry) and update it before apply.
resource "google_cloud_run_v2_service" "app" {
  name     = "\${local.slug}-app"
  location = var.location

  template {
    containers {
      image = "storyshelf:latest"

      ports {
        container_port = 3000
      }

      resources {
        limits = {
          cpu    = "1"
          memory = "2Gi"
        }
      }
    }

    scaling {
      min_instance_count = 1
      max_instance_count = 3
    }
  }

  ingress = "INGRESS_TRAFFIC_ALL"
}
`;
}

export function generateGcpWorker(): string {
  return `${header()}# Worker polls the capture queue and renders with Playwright.
# Internal ingress only: it makes outbound calls (queue, database, storage).
resource "google_cloud_run_v2_service" "worker" {
  name     = "\${local.slug}-worker"
  location = var.location

  template {
    containers {
      image = "storyshelf-worker:latest"

      resources {
        limits = {
          cpu    = "2"
          memory = "4Gi"
        }
      }
    }

    scaling {
      min_instance_count = 1
      max_instance_count = 3
    }
  }

  ingress = "INGRESS_TRAFFIC_INTERNAL_ONLY"
}
`;
}

export function generateGcpDatabase(): string {
  return `${header()}# Cloud SQL Postgres, smallest shared-core tier (test-profile
# default — raise tier for production). The server connects with
# createPostgresDatabase({ url: <database_url output> }).
resource "random_password" "db" {
  length  = 32
  special = true
}

resource "google_sql_database_instance" "main" {
  name             = "\${local.slug}-db"
  region           = var.location
  database_version = "POSTGRES_16"

  settings {
    tier = "db-f1-micro"

    backup_configuration {
      enabled = true
    }

    ip_configuration {
      ipv4_enabled = true
      require_ssl  = true
    }
  }
}

resource "google_sql_database" "shelf" {
  name     = "shelf"
  instance = google_sql_database_instance.main.name
}

resource "google_sql_user" "shelf" {
  name     = "shelfadmin"
  instance = google_sql_database_instance.main.name
  password = random_password.db.result
}
`;
}

export function generateGcpStorage(): string {
  return `${header()}# Bucket for storybook bundles. force_destroy keeps the CI
# teardown working on non-empty buckets; versioning plus a 30-day
# lifecycle on transient builds mirrors the S3 reference stack.
resource "google_storage_bucket" "storybook" {
  name                        = "\${local.slug}-storybook"
  location                    = var.location
  force_destroy               = true
  public_access_prevention    = "enforced"
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  lifecycle_rule {
    action {
      type = "Delete"
    }

    condition {
      age           = 30
      matches_prefix = ["builds/"]
    }
  }
}
`;
}

export function generateGcpQueue(): string {
  return `${header()}# Pull subscription with dead-lettering: past max deliveries the
# message moves to the DLQ topic — the GCP analog of SQS + DLQ. The
# subscription name matches the scaffolded worker default. Grant the
# runtime service account Pub/Sub roles post-apply (see README).
resource "google_pubsub_topic" "capture" {
  name = "\${local.slug}-capture"
}

resource "google_pubsub_topic" "capture_dlq" {
  name = "\${local.slug}-capture-dlq"
}

resource "google_pubsub_subscription" "capture" {
  name  = "capture-jobs"
  topic = google_pubsub_topic.capture.id

  ack_deadline_seconds       = 300
  message_retention_duration = "604800s"

  dead_letter_policy {
    dead_letter_topic     = google_pubsub_topic.capture_dlq.id
    max_delivery_attempts = 5
  }
}
`;
}

export function generateGcpIdentity(): string {
  return `${header()}# Identity Platform tenant for OIDC sign-in. Skipped entirely
# when var.identity_tenant is empty (use any OIDC provider instead).
resource "google_identity_platform_tenant" "main" {
  count               = var.identity_tenant == "" ? 0 : 1
  display_name        = var.identity_tenant
  project             = var.gcp_project_id
  allow_password_signup = false
}
`;
}

export function generateGcpSecrets(): string {
  return `${header()}# Secret Manager: session secret, OIDC secret, break-glass admin
# token, and the Postgres password. Never check these into env files.
resource "google_secret_manager_secret" "shelf_secret" {
  secret_id = "\${local.slug}-secret"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "shelf_secret" {
  secret      = google_secret_manager_secret.shelf_secret.id
  secret_data = "change-me"
}

resource "google_secret_manager_secret" "oidc_client_secret" {
  secret_id = "\${local.slug}-oidc-client-secret"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "oidc_client_secret" {
  secret      = google_secret_manager_secret.oidc_client_secret.id
  secret_data = "change-me"
}

resource "google_secret_manager_secret" "admin_token" {
  secret_id = "\${local.slug}-admin-token"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "admin_token" {
  secret      = google_secret_manager_secret.admin_token.id
  secret_data = "change-me"
}

resource "google_secret_manager_secret" "db_password" {
  secret_id = "\${local.slug}-db-password"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "db_password" {
  secret      = google_secret_manager_secret.db_password.id
  secret_data = random_password.db.result
}
`;
}

export function generateGcpDns(): string {
  return `${header()}# Cloud DNS zone + app CNAME + domain mapping. Skipped entirely
# when var.domain_name is empty. Google issues the managed certificate
# automatically once the records resolve.
resource "google_dns_managed_zone" "main" {
  count       = var.domain_name == "" ? 0 : 1
  name        = "\${local.slug}-zone"
  dns_name    = "\${var.domain_name}."
  description = "\${var.project} app zone"
}

resource "google_dns_record_set" "app" {
  count        = var.domain_name == "" ? 0 : 1
  name         = "app.\${var.domain_name}."
  type         = "CNAME"
  ttl          = 300
  managed_zone = google_dns_managed_zone.main[0].name
  rrdatas      = ["\${trimsuffix(replace(google_cloud_run_v2_service.app.uri, "https://", ""), "/")}."]
}

resource "google_cloud_run_domain_mapping" "app" {
  count    = var.domain_name == "" ? 0 : 1
  location = var.location
  name     = "app.\${var.domain_name}"

  metadata {
    namespace = var.gcp_project_id
  }

  spec {
    route_name = google_cloud_run_v2_service.app.name
  }
}
`;
}

export function generateGcpOutputs(): string {
  return `${header()}# Outputs feed directly into the scaffolded server's env. Keys are
# a stable contract parsed by CI — do not rename (tests pin the set).
# Values are "" when the resource is not provisioned.
output "run_url" {
  value = google_cloud_run_v2_service.app.uri
}

output "gcs_bucket" {
  value = google_storage_bucket.storybook.name
}

output "pubsub_topic" {
  value = google_pubsub_topic.capture.id
}

output "pubsub_subscription" {
  value = google_pubsub_subscription.capture.id
}

output "database_url" {
  value     = "postgresql://shelfadmin:\${random_password.db.result}@\${google_sql_database_instance.main.public_ip_address}:5432/shelf?sslmode=require"
  sensitive = true
}

output "identity_tenant_id" {
  value = var.identity_tenant == "" ? "" : google_identity_platform_tenant.main[0].name
}
`;
}

export function generateGcpTfvarsExample(): string {
  return `# Copy to terraform.tfvars and fill in per environment.
# CI test profile: pass a unique project per run instead —
#   terraform plan -var "project=shelf-ci-$GITHUB_RUN_ID"
project          = "my-storyshelf"
gcp_project_id   = "my-gcp-project"
location         = "us-central1"
domain_name      = ""
identity_tenant  = ""
`;
}

function generateGcpEnvTable(): string {
  return `| Output | Env var | Adapter |
|---|---|---|
| \`gcs_bucket\` (+ \`GOOGLE_CLOUD_PROJECT\`) | \`GCS_BUCKET\` | \`storage-gcs\` |
| \`pubsub_topic\` / \`pubsub_subscription\` | topic \`capture-jobs\` + subscription (baked into scaffold) | \`queue-gcp\` |
| \`database_url\` | \`DATABASE_URL\` | \`db-postgres\` |
| \`identity_tenant_id\` | \`OIDC_ISSUER\` (Google tenant) / \`OIDC_CLIENT_ID\` | \`auth-oauth\` (generic OIDC) |
| Secret Manager | \`SECRET\` / \`OIDC_CLIENT_SECRET\` / \`ADMIN_TOKEN\` | sessions / OIDC / bootstrap |
`;
}

function generateGcpCiProfile(): string {
  return `## CI test profile

Smallest footprint, unique resources per run, documented destroy:

\`\`\`sh
export PROJECT="shelf-ci-$GITHUB_RUN_ID"   # unique prefix per run (all names derive from it)
terraform init
terraform plan -var "project=$PROJECT" -out=tfplan
terraform apply tfplan
terraform output -json   # or: npm run infra:outputs
# ... run live tests against the outputs ...
terraform destroy -var "project=$PROJECT" -auto-approve
\`\`\`

Cost notes: Cloud SQL runs the shared-core \`db-f1-micro\` tier and the
worker scales to a single instance; the bucket uses
\`force_destroy\` so teardown succeeds on non-empty buckets. Prefer a
fresh unique prefix per run.
`;
}

export function generateGcpReadme(project: string): string {
  return `# ${project} on Google Cloud

Scaffolded by \`storyshelf server init --target gcp\`.

## Next steps

\`\`\`sh
gcloud auth login
gcloud config set project <gcp-project-id>
cd terraform
terraform init
terraform plan -out=tfplan   # review before applying
terraform apply tfplan
\`\`\`

Grant the runtime service account Pub/Sub (publisher/subscriber), Cloud
SQL Client, and Secret Manager accessor roles post-apply — Terraform
creates the resources, IAM bindings stay with your org policy.

## Wire outputs into env

\`\`\`sh
terraform output -json   # or: npm run infra:outputs
\`\`\`

${generateGcpEnvTable()}
\`\`\`sh
npm install
npm start
\`\`\`

Authenticate with \`gcloud auth login\` (or workload identity / a
service-account key) — never check credentials into env files.

${generateGcpCiProfile()}`;
}

const GCP_FILES: ReadonlyArray<readonly [string, (options: GcpTerraformOptions) => string]> = [
  ["terraform/versions.tf", () => generateGcpVersions()],
  ["terraform/variables.tf", () => generateGcpVariables()],
  ["terraform/main.tf", () => generateGcpMain()],
  ["terraform/compute.tf", () => `${generateGcpApp()}${generateGcpWorker()}`],
  ["terraform/database.tf", () => generateGcpDatabase()],
  ["terraform/storage.tf", () => generateGcpStorage()],
  ["terraform/queue.tf", () => generateGcpQueue()],
  ["terraform/identity.tf", () => generateGcpIdentity()],
  ["terraform/secrets.tf", () => generateGcpSecrets()],
  ["terraform/dns.tf", () => generateGcpDns()],
  ["terraform/outputs.tf", () => generateGcpOutputs()],
  ["terraform/terraform.tfvars.example", () => generateGcpTfvarsExample()],
];

/** Generate every Terraform file for the GCP reference stack. */
export function generateGcpTerraformFiles(options: GcpTerraformOptions): TerraformFiles {
  const files: TerraformFiles = {};
  for (const [path, generate] of GCP_FILES) {
    files[path] = generate(options);
  }
  files["terraform/README.md"] = generateGcpReadme(options.project);
  return files;
}
