/**
 * Terraform scaffolding for the AWS reference stack (enterprise default).
 *
 * Pure string builders — no runtime dependencies. Emitted by
 * `storyshelf server init` when the deploy target is `aws`, alongside the
 * standard `server.ts` / `worker.ts` / `package.json` files.
 *
 * Reference stack: S3 (storage) + SQS + DLQ (capture queue) + Postgres
 * (RDS default, Aurora DSQL option) + ECS Fargate app/worker + ALB +
 * Cognito (auth) + Secrets Manager + CloudWatch. VPC is created unless
 * `vpcId` is supplied; Route 53 + ACM apply only when `domainName` is set.
 */

/** Options for the AWS Terraform scaffold. */
export interface AwsTerraformOptions {
  /** Project slug, used as a name prefix for all resources. */
  project: string;
  /** AWS region, e.g. `us-east-1`. */
  region: string;
  /** Postgres engine: battle-tested RDS by default, serverless DSQL option. */
  dbEngine: "rds" | "dsql";
  /** Existing VPC id. Empty creates a new VPC. */
  vpcId?: string;
  /** Public domain for the ALB. Empty leaves the ALB HTTP-only. */
  domainName?: string;
  /** SAML metadata URL for Cognito federation (Entra/Okta). Empty skips it. */
  samlMetadataUrl?: string;
}

/** A generated file: relative path → contents. */
export type TerraformFiles = Record<string, string>;

/** Terraform CLI version floor for the generated modules. */
export const TERRAFORM_REQUIRED_VERSION = ">= 1.9";

function header(): string {
  return `# Generated by \`storyshelf server init --target aws\`. Do not edit by hand;\n# re-run the scaffold or edit the generator in @storyshelf/cli.\n\n`;
}

export function generateAwsVersions(): string {
  return `${header()}terraform {
  required_version = "${TERRAFORM_REQUIRED_VERSION}"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.60"
    }
  }
}
`;
}

export function generateAwsVariables(): string {
  return `${header()}variable "project" {
  description = "Project slug, used as a name prefix for all resources."
  type        = string
}

variable "region" {
  description = "AWS region for all resources."
  type        = string
  default     = "us-east-1"
}

variable "db_engine" {
  description = "Postgres engine: \\"rds\\" (Aurora/RDS, VPC-isolated) or \\"dsql\\" (serverless)."
  type        = string
  default     = "rds"

  validation {
    condition     = contains(["rds", "dsql"], var.db_engine)
    error_message = "db_engine must be \\"rds\\" or \\"dsql\\"."
  }
}

variable "vpc_id" {
  description = "Existing VPC id. Empty creates a new VPC."
  type        = string
  default     = ""
}

variable "domain_name" {
  description = "Public domain for the ALB (Route 53 + ACM). Empty leaves the ALB HTTP-only."
  type        = string
  default     = ""
}

variable "saml_metadata_url" {
  description = "SAML metadata URL for Cognito federation (Entra/Okta). Empty skips federation."
  type        = string
  default     = ""
}
`;
}

export function generateAwsVpc(): string {
  return `${header()}# VPC: created unless var.vpc_id points at an existing one.
resource "aws_vpc" "main" {
  count                = var.vpc_id == "" ? 1 : 0
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = { Name = "\${var.project}-vpc" }
}

locals {
  vpc_id = var.vpc_id != "" ? var.vpc_id : aws_vpc.main[0].id
}
`;
}

/** ALB + ECS security groups and private data-plane endpoints. */
export function generateAwsSecurity(): string {
  return `${header()}resource "aws_security_group" "alb" {
  name        = "\${var.project}-alb"
  description = "ALB ingress"
  vpc_id      = local.vpc_id

  ingress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_security_group" "ecs" {
  name        = "\${var.project}-ecs"
  description = "ECS tasks: ALB ingress only"
  vpc_id      = local.vpc_id

  ingress {
    from_port       = 3000
    to_port         = 3000
    protocol        = "tcp"
    security_groups = [aws_security_group.alb.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
`;
}

/** Private data-plane endpoints (S3, SQS) off the public internet. */
export function generateAwsEndpoints(): string {
  return `${header()}# VPC endpoints keep data-plane traffic (S3, SQS) off the public internet.
resource "aws_vpc_endpoint" "s3" {
  vpc_id       = local.vpc_id
  service_name = "com.amazonaws.\${var.region}.s3"
}

resource "aws_vpc_endpoint" "sqs" {
  vpc_id            = local.vpc_id
  service_name      = "com.amazonaws.\${var.region}.sqs"
  security_group_ids = [aws_security_group.ecs.id]
}
`;
}

export function generateAwsStorage(): string {
  return `${header()}resource "aws_s3_bucket" "storybook" {
  bucket = "\${var.project}-storybook"
}

resource "aws_s3_bucket_versioning" "storybook" {
  bucket = aws_s3_bucket.storybook.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "storybook" {
  bucket = aws_s3_bucket.storybook.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "storybook" {
  bucket                  = aws_s3_bucket.storybook.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Transient build bundles expire; baselines persist.
resource "aws_s3_bucket_lifecycle_configuration" "storybook" {
  bucket = aws_s3_bucket.storybook.id

  rule {
    id     = "expire-transient-builds"
    status = "Enabled"

    filter {
      prefix = "builds/"
    }

    expiration {
      days = 30
    }
  }
}
`;
}

export function generateAwsQueue(): string {
  return `${header()}resource "aws_sqs_queue" "capture_dlq" {
  name = "\${var.project}-capture-dlq"
}

resource "aws_sqs_queue" "capture" {
  name                       = "\${var.project}-capture"
  visibility_timeout_seconds = 300
  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.capture_dlq.arn
    maxReceiveCount     = 3
  })
}
`;
}

export function generateAwsDatabase(dbEngine: "rds" | "dsql"): string {
  if (dbEngine === "dsql") {
    return `${header()}# Serverless Postgres. The server connects with
# createPostgresDatabase({ url: <cluster endpoint> }).
resource "aws_dsql_cluster" "main" {
  deletion_protection_enabled = true

  tags = { Name = "\${var.project}-db" }
}
`;
  }
  return `${header()}# VPC-isolated Postgres for regulated estates. The server connects with
# createPostgresDatabase({ url: <DATABASE_URL with sslmode=require> }).
resource "aws_db_subnet_group" "main" {
  name       = "\${var.project}-db"
  subnet_ids = data.aws_subnets.private.ids
}

resource "aws_db_instance" "main" {
  identifier             = "\${var.project}-db"
  engine                 = "postgres"
  engine_version         = "16"
  instance_class         = "db.t4g.micro"
  allocated_storage      = 20
  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.ecs.id]
  skip_final_snapshot    = true
}
`;
}

export function generateAwsIdentity(): string {
  return `${header()}# Cognito User Pool: the enterprise identity front door. Federate a
# corporate IdP (Entra/Okta) via SAML by setting var.saml_metadata_url.
resource "aws_cognito_user_pool" "main" {
  name = "\${var.project}-users"
}

resource "aws_cognito_user_pool_client" "shelf" {
  name            = "\${var.project}-shelf"
  user_pool_id    = aws_cognito_user_pool.main.id
  generate_secret = true

  allowed_oauth_flows                  = ["code"]
  allowed_oauth_scopes                 = ["openid", "email", "profile"]
  callback_urls                        = ["https://\${var.domain_name == "" ? aws_lb.main.dns_name : var.domain_name}/auth/callback"]
  supported_identity_providers         = ["COGNITO"]
}

resource "aws_cognito_user_group" "admins" {
  name         = "shelf-admins"
  user_pool_id = aws_cognito_user_pool.main.id
}

resource "aws_cognito_identity_provider" "saml" {
  count         = var.saml_metadata_url == "" ? 0 : 1
  user_pool_id  = aws_cognito_user_pool.main.id
  provider_name = "CorporateSAML"
  provider_type = "SAML"

  provider_details = {
    MetadataURL = var.saml_metadata_url
  }
}
`;
}

export function generateAwsCompute(): string {
  return `${header()}# ECS Fargate: long-lived app + worker services. Playwright/Chromium
# renders on Fargate — Lambda's 15-minute limit and /tmp caps rule it out.
resource "aws_lb" "main" {
  name               = "\${var.project}-alb"
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = data.aws_subnets.public.ids
}

resource "aws_ecs_cluster" "main" {
  name = "\${var.project}-cluster"
}

resource "aws_cloudwatch_log_group" "app" {
  name              = "/ecs/\${var.project}-app"
  retention_in_days = 30
}

resource "aws_cloudwatch_log_group" "worker" {
  name              = "/ecs/\${var.project}-worker"
  retention_in_days = 30
}
`;
}

export function generateAwsSecrets(): string {
  return `${header()}# Secrets Manager: session secret, OIDC secret, break-glass admin
# token. Task roles below may read exactly these ARNs.
resource "aws_secretsmanager_secret" "shelf_secret" {
  name = "\${var.project}/SECRET"
}

resource "aws_secretsmanager_secret" "oidc_client_secret" {
  name = "\${var.project}/OIDC_CLIENT_SECRET"
}

resource "aws_secretsmanager_secret" "admin_token" {
  name = "\${var.project}/ADMIN_TOKEN"
}
`;
}

export function generateAwsDns(): string {
  return `${header()}# Route 53 + ACM. Skipped entirely when var.domain_name is empty
# (the ALB stays HTTP-only for dev).
resource "aws_acm_certificate" "main" {
  count             = var.domain_name == "" ? 0 : 1
  domain_name       = var.domain_name
  validation_method = "DNS"
}

resource "aws_route53_zone" "main" {
  count = var.domain_name == "" ? 0 : 1
  name  = var.domain_name
}

resource "aws_route53_record" "app" {
  count   = var.domain_name == "" ? 0 : 1
  zone_id = aws_route53_zone.main[0].zone_id
  name    = var.domain_name
  type    = "A"

  alias {
    name                   = aws_lb.main.dns_name
    zone_id                = aws_lb.main.zone_id
    evaluate_target_health = true
  }
}
`;
}

export function generateAwsOutputs(): string {
  return `${header()}# Outputs feed directly into the scaffolded server's env.
output "alb_dns_name" {
  value = aws_lb.main.dns_name
}

output "s3_bucket" {
  value = aws_s3_bucket.storybook.id
}

output "queue_url" {
  value = aws_sqs_queue.capture.url
}

output "user_pool_id" {
  value = aws_cognito_user_pool.main.id
}

output "app_client_id" {
  value = aws_cognito_user_pool_client.shelf.id
}
`;
}

export function generateAwsReadme(project: string): string {
  return `# ${project} on AWS

Scaffolded by \`storyshelf server init --target aws\`.

## Next steps

\`\`\`sh
cd terraform
terraform init
terraform plan -out=tfplan   # review before applying
terraform apply tfplan
\`\`\`

## Wire outputs into env

\`\`\`sh
terraform output -json   # or: npm run infra:outputs
\`\`\`

| Output | Env var | Adapter |
|---|---|---|
| \`s3_bucket\` | \`S3_BUCKET\` (+ \`AWS_REGION\`) | \`storage-s3\` |
| \`queue_url\` | \`QUEUE_URL\` | \`queue-sqs\` |
| db endpoint | \`DATABASE_URL\` (\`?sslmode=require\`) | \`db-postgres\` |
| \`user_pool_id\` / \`app_client_id\` | \`COGNITO_USER_POOL_ID\` / \`OIDC_CLIENT_ID\` | \`auth-oauth\` (cognito preset) |
| Secrets Manager | \`SECRET\` / \`OIDC_CLIENT_SECRET\` / \`ADMIN_TOKEN\` | sessions / OIDC / bootstrap |

\`\`\`sh
npm install
npm start
\`\`\`

Credentials come from IAM (ECS task roles) — never check access keys into env files.
`;
}

const AWS_FILES: ReadonlyArray<readonly [string, (options: AwsTerraformOptions) => string]> = [
  ["terraform/versions.tf", () => generateAwsVersions()],
  ["terraform/variables.tf", () => generateAwsVariables()],
  [
    "terraform/network.tf",
    () => `${generateAwsVpc()}${generateAwsSecurity()}${generateAwsEndpoints()}`,
  ],
  ["terraform/storage.tf", () => generateAwsStorage()],
  ["terraform/queue.tf", () => generateAwsQueue()],
  ["terraform/identity.tf", () => generateAwsIdentity()],
  ["terraform/compute.tf", () => generateAwsCompute()],
  ["terraform/secrets.tf", () => generateAwsSecrets()],
  ["terraform/dns.tf", () => generateAwsDns()],
  ["terraform/outputs.tf", () => generateAwsOutputs()],
];

/** Generate every Terraform file for the AWS reference stack. */
export function generateAwsTerraformFiles(options: AwsTerraformOptions): TerraformFiles {
  const files: TerraformFiles = {};
  for (const [path, generate] of AWS_FILES) {
    files[path] = generate(options);
  }
  files["terraform/database.tf"] = generateAwsDatabase(options.dbEngine);
  files["terraform/README.md"] = generateAwsReadme(options.project);
  return files;
}
