import { TERRAFORM_REQUIRED_VERSION } from "./terraform-aws.ts";

/**
 * Terraform scaffolding for the Azure reference stack.
 *
 * Pure string builders — no runtime dependencies. Emitted by
 * `storyshelf server init` when the deploy target is `azure`, alongside the
 * standard `server.ts` / `worker.ts` / `package.json` files.
 *
 * Reference stack: Container Apps (app + worker) + Azure Blob Storage
 * (storybook bundles) + Storage Queues or Service Bus (capture queue,
 * selected by `queue_backend`) + Postgres Flexible Server + Key Vault +
 * Microsoft Entra app (only when `entra_tenant_id` is set) + DNS zone
 * (only when `domain_name` is set). Hostname binding + managed TLS is a
 * post-apply step (see the generated README); the scaffold stops at the
 * DNS records plus domain-verification TXT.
 *
 * Output contract (stable keys, parsed by CI — see `AZURE_TERRAFORM_OUTPUT_KEYS`):
 * keys are always present; values are `""` when the resource is not
 * provisioned for the selected backend / optional inputs.
 */

/** Queue backends supported by the Azure Terraform scaffold. */
export type AzureQueueBackend = "storage-queues" | "service-bus";

/** Options for the Azure Terraform scaffold. */
export interface AzureTerraformOptions {
  /** Project slug, used as a name prefix for all resources. */
  project: string;
  /** Azure region, e.g. `eastus`. */
  location: string;
  /** Capture queue backend. Baked at scaffold time (not a variable). */
  queueBackend: AzureQueueBackend;
  /** Public domain for the app. Empty leaves DNS out entirely. */
  domainName?: string;
  /** Entra tenant ID for the app registration. Empty skips identity. */
  entraTenantId?: string;
}

/** A generated file: relative path → contents. */
export type TerraformFiles = Record<string, string>;

/**
 * Stable `terraform output -json` keys. CI (`live-cloud.yml`) parses these;
 * renaming a key is a breaking change — the unit tests pin this list.
 */
export const AZURE_TERRAFORM_OUTPUT_KEYS: readonly string[] = [
  "app_fqdn",
  "database_url",
  "entra_application_id",
  "entra_tenant_id",
  "queue_name",
  "servicebus_connection_string",
  "storage_connection_string",
];

function header(): string {
  return `# Generated by \`storyshelf server init --target azure\`. Do not edit by hand;\n# re-run the scaffold or edit the generator in @storyshelf/cli.\n\n`;
}

export function generateAzureVersions(): string {
  return `${header()}terraform {
  required_version = "${TERRAFORM_REQUIRED_VERSION}"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">= 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
`;
}

export function generateAzureVariables(): string {
  return `${header()}variable "project" {
  description = "Project slug, used as a name prefix for all resources."
  type        = string
}

variable "location" {
  description = "Azure region for all resources."
  type        = string
  default     = "eastus"
}

variable "queue_backend" {
  description = "Capture queue backend: Storage Queues or Service Bus."
  type        = string
  default     = "storage-queues"

  validation {
    condition     = contains(["storage-queues", "service-bus"], var.queue_backend)
    error_message = "queue_backend must be storage-queues or service-bus."
  }
}

variable "domain_name" {
  description = "Public domain for the app (DNS zone + records). Empty skips DNS."
  type        = string
  default     = ""
}

variable "entra_tenant_id" {
  description = "Entra tenant ID for the app registration. Empty skips identity."
  type        = string
  default     = ""
}
`;
}

export function generateAzureMain(): string {
  return `${header()}# One resource group per project. Storage account names allow only
# lowercase alphanumerics, so alphanum is the sanitized prefix.
resource "azurerm_resource_group" "main" {
  name     = "\${local.slug}-rg"
  location = var.location
}

locals {
  slug     = lower(var.project)
  alphanum = substr(replace(local.slug, "/[^a-z0-9]/", ""), 0, 16)
}
`;
}

export function generateAzureMonitoring(): string {
  return `${header()}resource "azurerm_log_analytics_workspace" "main" {
  name                = "\${local.slug}-law"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "main" {
  name                       = "\${local.slug}-cae"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.main.id
}
`;
}

export function generateAzureApp(): string {
  return `${header()}# App with external ingress. Image is a placeholder: push the
# scaffolded Dockerfile to ACR and update it before applying.
resource "azurerm_container_app" "app" {
  name                         = "\${local.slug}-app"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  template {
    container {
      name   = "app"
      image  = "storyshelf:latest"
      cpu    = 1
      memory = "2Gi"
    }
  }

  ingress {
    external    = true
    target_port = 3000

    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }
}
`;
}

export function generateAzureWorker(): string {
  return `${header()}# Worker polls the capture queue and renders with Playwright.
# No ingress: it only makes outbound calls (queue, database, storage).
resource "azurerm_container_app" "worker" {
  name                         = "\${local.slug}-worker"
  container_app_environment_id = azurerm_container_app_environment.main.id
  resource_group_name          = azurerm_resource_group.main.name
  revision_mode                = "Single"

  template {
    min_replicas = 1

    container {
      name   = "worker"
      image  = "storyshelf-worker:latest"
      cpu    = 2
      memory = "4Gi"
    }
  }
}
`;
}

export function generateAzureDatabase(): string {
  return `${header()}# Postgres Flexible Server, smallest burstable SKU (test-profile
# default — raise sku_name for production). The server connects with
# createPostgresDatabase({ url: <db_endpoint output> }).
resource "random_password" "db" {
  length  = 32
  special = true
}

resource "azurerm_postgresql_flexible_server" "main" {
  name                   = "\${local.slug}-db"
  resource_group_name    = azurerm_resource_group.main.name
  location               = azurerm_resource_group.main.location
  version                = "16"
  administrator_login    = "shelfadmin"
  administrator_password = random_password.db.result
  storage_mb             = 32768
  sku_name               = "B_Standard_B1ms"
  backup_retention_days  = 7
}

resource "azurerm_postgresql_flexible_server_firewall_rule" "azure_services" {
  name             = "allow-azure-services"
  server_id        = azurerm_postgresql_flexible_server.main.id
  start_ip_address = "0.0.0.0"
  end_ip_address   = "0.0.0.0"
}

resource "azurerm_postgresql_flexible_server_database" "shelf" {
  name      = "shelf"
  server_id = azurerm_postgresql_flexible_server.main.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}
`;
}

export function generateAzureStorage(): string {
  return `${header()}# Blob container for storybook bundles + the Storage Queues
# backend (created only when var.queue_backend selects it). The queue
# name matches the scaffolded server default ("capture-jobs").
resource "azurerm_storage_account" "main" {
  name                     = "\${local.alphanum}shlf"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
}

resource "azurerm_storage_container" "storybook" {
  name               = "storybook"
  storage_account_id = azurerm_storage_account.main.id
}

resource "azurerm_storage_queue" "capture" {
  count              = var.queue_backend == "storage-queues" ? 1 : 0
  name               = "capture-jobs"
  storage_account_id = azurerm_storage_account.main.id
}
`;
}

export function generateAzureQueue(): string {
  return `${header()}# Service Bus backend (created only when var.queue_backend
# selects it). max_delivery_count dead-letters poison messages to the
# built-in DLQ sub-queue — the Azure analog of the SQS + DLQ pattern.
resource "azurerm_servicebus_namespace" "main" {
  count               = var.queue_backend == "service-bus" ? 1 : 0
  name                = "\${local.slug}-sb"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku                 = "Standard"
}

resource "azurerm_servicebus_queue" "capture" {
  count                                = var.queue_backend == "service-bus" ? 1 : 0
  name                                 = "capture-jobs"
  namespace_id                         = azurerm_servicebus_namespace.main[0].id
  max_delivery_count                   = 3
  dead_lettering_on_message_expiration = true
}
`;
}

export function generateAzureIdentity(): string {
  return `${header()}# Microsoft Entra app registration for OIDC. Skipped entirely
# when var.entra_tenant_id is empty (use any OIDC provider instead).
data "azurerm_client_config" "current" {}

resource "azuread_application" "shelf" {
  count        = var.entra_tenant_id == "" ? 0 : 1
  display_name = "\${var.project}-shelf"
}

resource "azuread_service_principal" "shelf" {
  count     = var.entra_tenant_id == "" ? 0 : 1
  client_id = azuread_application.shelf[0].client_id
}
`;
}

export function generateAzureSecrets(): string {
  return `${header()}# Key Vault: session secret, OIDC secret, break-glass admin
# token, and the Postgres password. Never check these into env files.
resource "azurerm_key_vault" "main" {
  name                       = "\${local.slug}-kv"
  location                   = azurerm_resource_group.main.location
  resource_group_name        = azurerm_resource_group.main.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  enable_rbac_authorization  = true
  soft_delete_retention_days = 7
}

resource "azurerm_key_vault_secret" "shelf_secret" {
  name         = "SECRET"
  value        = "change-me"
  key_vault_id = azurerm_key_vault.main.id
}

resource "azurerm_key_vault_secret" "oidc_client_secret" {
  name         = "OIDC_CLIENT_SECRET"
  value        = "change-me"
  key_vault_id = azurerm_key_vault.main.id
}

resource "azurerm_key_vault_secret" "admin_token" {
  name         = "ADMIN_TOKEN"
  value        = "change-me"
  key_vault_id = azurerm_key_vault.main.id
}

resource "azurerm_key_vault_secret" "db_password" {
  name         = "DB_PASSWORD"
  value        = random_password.db.result
  key_vault_id = azurerm_key_vault.main.id
}
`;
}

export function generateAzureDns(): string {
  return `${header()}# DNS zone + verification TXT + app CNAME. Skipped entirely when
# var.domain_name is empty. Hostname binding + managed TLS is a
# post-apply step (see README): the records below are its prerequisite.
resource "azurerm_dns_zone" "main" {
  count               = var.domain_name == "" ? 0 : 1
  name                = var.domain_name
  resource_group_name = azurerm_resource_group.main.name
}

resource "azurerm_dns_txt_record" "verify" {
  count               = var.domain_name == "" ? 0 : 1
  name                = "asuid.app"
  zone_name           = azurerm_dns_zone.main[0].name
  resource_group_name = azurerm_resource_group.main.name
  ttl                 = 300

  record {
    value = azurerm_container_app_environment.main.custom_domain_verification_id
  }
}

resource "azurerm_dns_cname_record" "app" {
  count               = var.domain_name == "" ? 0 : 1
  name                = "app"
  zone_name           = azurerm_dns_zone.main[0].name
  resource_group_name = azurerm_resource_group.main.name
  ttl                 = 300
  record              = azurerm_container_app.app.latest_revision_fqdn
}
`;
}

export function generateAzureOutputs(): string {
  return `${header()}# Outputs feed directly into the scaffolded server's env. Keys are
# a stable contract parsed by CI — do not rename (tests pin the set).
# Values are "" when the resource is not provisioned for this backend.
output "app_fqdn" {
  value = azurerm_container_app.app.latest_revision_fqdn
}

output "storage_connection_string" {
  value     = azurerm_storage_account.main.primary_connection_string
  sensitive = true
}

output "servicebus_connection_string" {
  value     = var.queue_backend == "service-bus" ? azurerm_servicebus_namespace.main[0].default_primary_connection_string : ""
  sensitive = true
}

output "queue_name" {
  value = "capture-jobs"
}

output "database_url" {
  value     = "postgresql://shelfadmin:\${random_password.db.result}@\${azurerm_postgresql_flexible_server.main.fqdn}:5432/shelf?sslmode=require"
  sensitive = true
}

output "entra_application_id" {
  value = var.entra_tenant_id == "" ? "" : azuread_application.shelf[0].client_id
}

output "entra_tenant_id" {
  value = var.entra_tenant_id
}
`;
}

export function generateAzureTfvarsExample(): string {
  return `# Copy to terraform.tfvars and fill in per environment.
# CI test profile: pass a unique project per run instead —
#   terraform plan -var "project=shelf-ci-$GITHUB_RUN_ID"
project         = "my-storyshelf"
location        = "eastus"
queue_backend   = "storage-queues" # or "service-bus"
domain_name     = ""
entra_tenant_id = ""
`;
}

function generateAzureEnvTable(queueBackend: AzureQueueBackend): string {
  const queueRow =
    queueBackend === "service-bus"
      ? "| `servicebus_connection_string` | `AZURE_SERVICE_BUS_CONNECTION` | `queue-azure` (service-bus) |"
      : "| `storage_connection_string` | `AZURE_STORAGE_CONNECTION` | `queue-azure` (storage-queues) + `storage-azure` |";
  return `| Output | Env var | Adapter |
|---|---|---|
| \`storage_connection_string\` | \`AZURE_STORAGE_CONNECTION\` | \`storage-azure\` (Blob container) |
${queueRow}
| \`queue_name\` | (baked into scaffold as \`"capture-jobs"\`) | \`queue-azure\` |
| \`database_url\` | \`DATABASE_URL\` | \`db-postgres\` |
| \`entra_application_id\` / \`entra_tenant_id\` | \`OIDC_CLIENT_ID\` / \`OIDC_ISSUER\` (\`https://login.microsoftonline.com/{tenant}/v2.0\`) | \`auth-oauth\` (generic OIDC) |
| Key Vault | \`SECRET\` / \`OIDC_CLIENT_SECRET\` / \`ADMIN_TOKEN\` | sessions / OIDC / bootstrap |
`;
}

function generateAzureCiProfile(): string {
  return `## CI test profile

Smallest footprint, unique resources per run, documented destroy:

\`\`\`sh
export PROJECT="shelf-ci-$GITHUB_RUN_ID"   # unique prefix per run (all names derive from it)
terraform init
terraform plan -var "project=$PROJECT" -out=tfplan
terraform apply tfplan
terraform output -json   # or: npm run infra:outputs
# ... run live tests against the outputs ...
terraform destroy -var "project=$PROJECT" -auto-approve
\`\`\`

Cost notes: Postgres Flexible is the B1ms burstable SKU, Container Apps
run on consumption, and the worker scales to a single replica. Key Vault
uses 7-day soft-delete so re-running with the same project name within a
week reuses the vault (prefer a fresh unique prefix per run).
`;
}

export function generateAzureReadme(project: string, queueBackend: AzureQueueBackend): string {
  return `# ${project} on Azure

Scaffolded by \`storyshelf server init --target azure\`.

## Next steps

\`\`\`sh
az login
cd terraform
terraform init
terraform plan -out=tfplan   # review before applying
terraform apply tfplan
\`\`\`

## Wire outputs into env

\`\`\`sh
terraform output -json   # or: npm run infra:outputs
\`\`\`

${generateAzureEnvTable(queueBackend)}
\`\`\`sh
npm install
npm start
\`\`\`

Authenticate with \`az login\` (or a service principal / managed identity) —
never check connection strings into env files.

## Custom domain

The scaffold creates the DNS zone plus verification records. After
applying, bind the hostname and let Container Apps issue the managed
certificate (portal, or \`az containerapp hostname add\` once the CNAME
resolves).

${generateAzureCiProfile()}`;
}

const AZURE_FILES: ReadonlyArray<readonly [string, (options: AzureTerraformOptions) => string]> = [
  ["terraform/versions.tf", () => generateAzureVersions()],
  ["terraform/variables.tf", () => generateAzureVariables()],
  ["terraform/main.tf", () => generateAzureMain()],
  [
    "terraform/compute.tf",
    () => `${generateAzureMonitoring()}${generateAzureApp()}${generateAzureWorker()}`,
  ],
  ["terraform/database.tf", () => generateAzureDatabase()],
  ["terraform/storage.tf", () => generateAzureStorage()],
  ["terraform/queue.tf", () => generateAzureQueue()],
  ["terraform/identity.tf", () => generateAzureIdentity()],
  ["terraform/secrets.tf", () => generateAzureSecrets()],
  ["terraform/dns.tf", () => generateAzureDns()],
  ["terraform/outputs.tf", () => generateAzureOutputs()],
  ["terraform/terraform.tfvars.example", () => generateAzureTfvarsExample()],
];

/** Generate every Terraform file for the Azure reference stack. */
export function generateAzureTerraformFiles(options: AzureTerraformOptions): TerraformFiles {
  const files: TerraformFiles = {};
  for (const [path, generate] of AZURE_FILES) {
    files[path] = generate(options);
  }
  files["terraform/README.md"] = generateAzureReadme(options.project, options.queueBackend);
  return files;
}
