import { libConfig } from "../../config/tsdown.ts";

export default libConfig({
  index: "./src/index.tsx",
  ai: "./src/ai.ts",
  insights: "./src/insights/index.ts",
  auth: "./src/auth.ts",
  "adapter/metadata": "./src/adapters/metadata.ts",
  "adapter/setup": "./src/adapters/setup.ts",
  "adapter/database": "./src/adapters/database.ts",
  "adapter/storage": "./src/adapters/storage.ts",
  "adapter/capture-runner": "./src/adapters/capture-runner.ts",
  "adapter/git-host": "./src/adapters/git-host/index.ts",
  "adapter/git-host/helpers": "./src/adapters/git-host/helpers.ts",
  "adapter/git-host/comments": "./src/adapters/git-host/comments.ts",
  "adapter/capture-queue": "./src/adapters/capture-queue.ts",
  "adapter/webhook-events": "./src/adapters/webhook-events.ts",
  "adapter/notifier": "./src/adapters/notifier/index.ts",
  "adapter/email-sender": "./src/adapters/email-sender.ts",
  logger: "./src/logger.ts",
  capture: "./src/capture/index.ts",
  config: "./src/config.ts",
  diff: "./src/diff/index.ts",
  models: "./src/models/index.ts",
  retention: "./src/retention/purge.ts",
  orm: "./src/orm/index.ts",
  "orm/pg-core": "./src/orm/pg-core.ts",
  "orm/sqlite-core": "./src/orm/sqlite-core.ts",
  paths: "./src/utils/paths.ts",
  urls: "./src/urls.ts",
  schema: "./src/schema/index.ts",
  types: "./src/types.ts",
  utils: "./src/utils/index.ts",
  "test-helpers": "./src/test-helpers/index.ts",
});
