import starlight from "@astrojs/starlight";
import mermaid from "astro-mermaid";
import { defineConfig } from "astro/config";
import starlightImageZoom from "starlight-image-zoom";
import starlightLinksValidator from "starlight-links-validator";
import starlightOpenAPI, { openAPISidebarGroups } from "starlight-openapi";

const SITE = "https://storyshelf.js.org";
const REPO = "https://github.com/GuptaSiddhant/StoryShelf";
const OG_IMAGE = `${SITE}/og-image.png`;
const OG_ALT = "StoryShelf: visual testing for Storybook, with the build review workspace";

/** Packages grouped by the adapter slot they fill. */
const packageGroup = (label, slugs) => ({
  label,
  collapsed: true,
  items: slugs.map((slug) => ({ label: `@storyshelf/${slug}`, slug: `packages/${slug}` })),
});

export default defineConfig({
  site: SITE,
  base: process.env.BASE_PATH || "/",
  // The API reference used to be a standalone Swagger page at /openapi/.
  redirects: {
    "/openapi": "/api/",
    "/guides/ai-insights": "/ai/",
    "/guides/ai-testing": "/ai/testing/",
  },
  integrations: [
    mermaid({ autoTheme: true }),
    starlight({
      title: "StoryShelf",
      description: "Self-hosted visual testing for Storybook.",
      logo: { src: "./src/assets/logo.svg", alt: "" },
      components: {
        Hero: "./src/components/overrides/Hero.astro",
        SocialIcons: "./src/components/overrides/SocialIcons.astro",
        Sidebar: "./src/components/overrides/Sidebar.astro",
      },
      customCss: ["./src/styles/custom.css"],
      editLink: { baseUrl: `${REPO}/edit/main/apps/website/` },
      lastUpdated: true,
      social: [{ label: "GitHub", href: REPO, icon: "github" }],
      // Starlight emits og:title/description/url/type, the sitemap and the SVG
      // favicon itself; these add the raster icon fallbacks (Safari, older
      // browsers, home screens) plus the social image and card type.
      head: [
        { tag: "link", attrs: { rel: "icon", href: "/favicon.ico", sizes: "32x32" } },
        {
          tag: "link",
          attrs: { rel: "icon", type: "image/png", sizes: "16x16", href: "/favicon-16.png" },
        },
        {
          tag: "link",
          attrs: { rel: "icon", type: "image/png", sizes: "32x32", href: "/favicon-32.png" },
        },
        {
          tag: "link",
          attrs: { rel: "apple-touch-icon", sizes: "180x180", href: "/apple-touch-icon.png" },
        },
        { tag: "meta", attrs: { name: "theme-color", content: "#1d5fcf" } },
        {
          // Tables that scroll sideways on narrow screens must be keyboard-focusable.
          tag: "script",
          content:
            "addEventListener('DOMContentLoaded',()=>{for(const t of document.querySelectorAll('.sl-markdown-content table'))t.tabIndex=0})",
        },
        { tag: "meta", attrs: { property: "og:image", content: OG_IMAGE } },
        { tag: "meta", attrs: { property: "og:image:width", content: "1200" } },
        { tag: "meta", attrs: { property: "og:image:height", content: "630" } },
        { tag: "meta", attrs: { property: "og:image:alt", content: OG_ALT } },
        { tag: "meta", attrs: { name: "twitter:card", content: "summary_large_image" } },
        { tag: "meta", attrs: { name: "twitter:image", content: OG_IMAGE } },
        { tag: "meta", attrs: { name: "twitter:image:alt", content: OG_ALT } },
      ],
      plugins: [
        starlightImageZoom(),
        starlightOpenAPI([
          {
            base: "api",
            label: "API reference",
            // Generated from the app's routes by `prebuild` / `predev` (see package.json).
            schema: "./public/openapi.json",
            // "GET Create a build" style labels instead of repeating the path per method.
            sidebar: { operations: { badges: true, labels: "summary" } },
          },
        ]),
        // Last, so it validates the pages the other plugins generate too.
        // /api/** is generated by starlight-openapi, which the validator cannot see.
        starlightLinksValidator({ errorOnRelativeLinks: false, exclude: ["/api/**"] }),
      ],
      sidebar: [
        {
          label: "Start here",
          items: [
            { label: "Getting started", slug: "guides/getting-started" },
            { label: "Live demo", slug: "guides/demo" },
          ],
        },
        {
          label: "Guides",
          items: [
            {
              label: "Review workflow",
              collapsed: true,
              items: [
                { label: "CI setup", slug: "guides/ci" },
                { label: "Reviewing changes", slug: "guides/review" },
                { label: "Merge gate", slug: "guides/merge-gate" },
                { label: "Interaction testing", slug: "guides/interaction-testing" },
                { label: "Notifications", slug: "guides/notifications" },
                { label: "Without git", slug: "guides/without-git" },
              ],
            },
            {
              label: "Projects & CLI",
              collapsed: true,
              items: [
                { label: "Project settings", slug: "guides/project-settings" },
                { label: "Configuration", slug: "guides/config" },
                { label: "CLI overview", slug: "guides/cli" },
                { label: "CLI client", slug: "guides/cli/client" },
                { label: "CLI server", slug: "guides/cli/server" },
              ],
            },
            {
              label: "Deployment",
              collapsed: true,
              items: [
                { label: "Overview", slug: "guides/deployment" },
                { label: "Docker Compose", slug: "guides/deployment/docker-compose" },
                { label: "Remote workers", slug: "guides/deployment/remote-workers" },
                { label: "AWS", slug: "guides/deployment/aws" },
                { label: "Azure", slug: "guides/deployment/azure" },
                { label: "GCP", slug: "guides/deployment/gcp" },
                { label: "Cloud assembly", slug: "guides/deployment/cloud" },
                { label: "Observability", slug: "guides/observability" },
                { label: "Secret rotation", slug: "guides/deployment/secret-rotation" },
              ],
            },
            {
              label: "Authentication",
              collapsed: true,
              items: [
                { label: "Overview", slug: "guides/auth" },
                { label: "Local accounts", slug: "guides/auth/local" },
                { label: "Social login", slug: "guides/auth/social" },
                { label: "OIDC", slug: "guides/auth/oidc" },
                { label: "SAML", slug: "guides/auth/saml" },
                { label: "Passkeys", slug: "guides/auth/passkeys" },
                { label: "Configuration", slug: "guides/auth/configuration" },
              ],
            },
            {
              label: "Coming from Chromatic",
              collapsed: true,
              items: [
                { label: "Comparison", slug: "guides/chromatic-comparison" },
                { label: "Migration", slug: "guides/chromatic-migration" },
              ],
            },
          ],
        },
        {
          label: "AI insights",
          items: [
            { label: "Overview", slug: "ai" },
            { label: "Setup and providers", slug: "ai/setup" },
            { label: "Build triage", slug: "ai/triage" },
            { label: "Project health", slug: "ai/health" },
            { label: "Privacy and safety", slug: "ai/privacy" },
            { label: "Budget and usage", slug: "ai/budget" },
            { label: "AI API", slug: "ai/api" },
            { label: "MCP server", slug: "ai/mcp" },
            { label: "Free AI for testing", slug: "ai/testing" },
          ],
        },
        {
          label: "Core concepts",
          collapsed: true,
          items: [
            { label: "Projects", slug: "concepts/projects" },
            { label: "Builds & snapshots", slug: "concepts/builds" },
            { label: "Capture & viewports", slug: "concepts/capture" },
            { label: "Affected capture", slug: "concepts/affected-capture" },
            { label: "Baselines & branches", slug: "concepts/baselines" },
            { label: "Labels", slug: "concepts/labels" },
            { label: "Retention & purge", slug: "concepts/retention" },
            { label: "Published Storybook", slug: "concepts/publishing" },
            { label: "Roles & tokens", slug: "concepts/roles" },
            { label: "Authentication model", slug: "concepts/auth" },
          ],
        },
        {
          label: "Reference",
          items: [
            { label: "REST API", slug: "guides/api" },
            { label: "Webhooks", slug: "guides/webhooks" },
            { label: "Changelog", slug: "changelog" },
          ],
        },
        // Shown on /api/** only (see components/overrides/Sidebar.astro).
        ...openAPISidebarGroups,
        {
          label: "Packages",
          collapsed: true,
          items: [
            packageGroup("Core", [
              "core",
              "app",
              "affected",
              "worker",
              "observability",
              "auth",
              "ai",
              "mcp",
            ]),
            { label: "storyshelf (CLI)", slug: "packages/cli" },
            packageGroup("Databases", ["db-sqlite", "db-postgres", "db-mysql"]),
            packageGroup("Storage", [
              "storage-local",
              "storage-s3",
              "storage-azure",
              "storage-gcs",
            ]),
            packageGroup("Queues", ["queue-sqs", "queue-redis", "queue-azure", "queue-gcp"]),
            packageGroup("Capture runners", ["runner-playwright", "runner-puppeteer"]),
            packageGroup("Git hosts", ["git-github", "git-gitlab"]),
            packageGroup("Notifications", ["notify-chat", "notify-email"]),
          ],
        },
      ],
    }),
  ],
});
